### ISSUE TITLE
Templates copied with IDs different from source

### ISSUE THREAD

**Issue by simonemazzoni** [astrocaribe/template_transfer#1]
Hello, 
I noticed that all the templates are copied correctly to the destination account but with a different ID.
I think that up to now isn't possible to do better than this according to Sendgrid APIs.
Am I right? Or there is a way to copy the template maintaining the same ID between source and destination?

Thanks for the answer.

Simone

**Comment by astrocaribe** [comment]
Hey simonemazzoni,

The template IDs in one account are unique to that account. As such, creating (or as in this case) copying templates to a separate account generates a new ID, unique to the second account. So you are indeed correct, it is not possible to sync template IDs across accounts.

I'm happy that the script is of use to you, please let me know if you have any other questions!

Tommy...

**Comment by astrocaribe** [comment]
Closing this issue, please feel free to let me know if you have any other questions, or reopen if there is action to be taken.

**Comment by simonemazzoni** [comment]
Hello Tommy,
thanks for the answer. I opened a ticket on Sendgrid forum signaling the need of a easier way to migrate templates between accounts. I'll let you know if they answer me.

Simone
